"""create tenant users table

Revision ID: e9e1f6ce6259
Revises: e3d1dea98f2b
Create Date: 2026-10-09 12:26:34.073213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e1f6ce6259'
down_revision: Union[str, Sequence[str], None] = 'e3d1dea98f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='OPERATOR', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'OPERATOR')", name='ck_tenant_users_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED')", name='ck_tenant_users_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_users_tenant_user')
    )
    op.create_index('ix_tenant_users_tenant_id', 'tenant_users', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_users_user_id', 'tenant_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenant_users_user_id', table_name='tenant_users')
    op.drop_index('ix_tenant_users_tenant_id', table_name='tenant_users')
    op.drop_table('tenant_users')
    # ### end Alembic commands ###
